### PR TITLE
updated color definitions (background and fonts)

### PR DESCRIPTION
**Pull request by farvardin**

### CODE REVIEW

**Comment by farvardin** [comment]
it should work now (almost)

**Comment by farvardin** [comment]
I've added more color schemes and tried to improved the existing ones. You can review them and modify them further if you wish.

**Comment by farvardin** [comment]
promis, j'arrête après...

**Comment by yoyz** [comment]
I try this, seem to works fine and looks really good ;)

**Comment by yoyz** [comment]
I try it at home with my psp, if everything works, I push a new tag picoloop 0.74b.
PSP binary need padding, so I will need to push one or two commit more before releasing.
And by the way, if you are able to create a binary for pocketchip I will upload it.
Thanks for the new color scheme, looks really great, I like the grey one  :)

**Pull request merged**
